#!/bin/bash

# FreePBX (version 2.8) start at boot script for Debian (version 5 Lenny)

### BEGIN INIT INFO
# Provides:          amportal
# Required-Start:    $local_fs $remote_fs fonulator dahdi
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop AsteriskManagerPortal
# Description:       Start/stop AsteriskManagerPortal
### END INIT INFO


start_instance () {

    /usr/local/sbin/amportal start
    rasterisk -x "core waitfullybooted"
    /usr/local/sbin/voipConfigMaker
}

stop_instance () {

    /usr/local/sbin/amportal stop

}

case "$1" in
    start)
        echo -n "Starting amportal"
        start_instance
        echo "."
        ;;
    stop)
        echo -n "Stopping amportal"
        stop_instance
        echo "."
        ;;
    restart)
        echo -n "Stopping amportal"
        stop_instance
        sleep 1
        echo "."
        echo -n "Starting amportal"
        start_instance
        echo "."
        ;;
    force-reload)
        echo -n "Stopping amportal"
        stop_instance
        sleep 1
        echo "."
        echo -n "Starting amportal"
        start_instance
        echo "."
        ;;
    *)
    echo "Usage: /etc/init.d/amportal {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
